"use client";

import { ReactNode } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Toaster } from "sonner";
import { AuthButton } from "../auth/auth-button";
import { WalletButton } from "../solana/solana-provider";
import { ClusterChecker } from "../cluster/cluster-ui";
import { AccountChecker } from "../account/account-ui";

export function AppLayout({
  children,
  links,
}: {
  children: ReactNode;
  links: { label: string; path: string }[];
}) {
  const pathname = usePathname();

  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      {/* Header/Navbar */}
      <header className="border-b border-border bg-card/50 backdrop-blur-md sticky top-0 z-40">
        <div className="container mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-6">
            <Link href="/" className="font-bold text-xl">
              The Menageri3
            </Link>
            <nav className="hidden md:flex">
              <ul className="flex items-center gap-4">
                {links.map(({ label, path }) => (
                  <li key={path}>
                    <Link
                      href={path}
                      className={`px-2 py-1 rounded-md transition-colors ${
                        pathname.startsWith(path)
                          ? "bg-accent/10 text-accent-foreground font-medium"
                          : "hover:bg-accent/5 text-muted-foreground"
                      }`}
                    >
                      {label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          </div>

          <div className="flex items-center gap-2">
            <AuthButton />
            <WalletButton />
          </div>
        </div>
      </header>

      {/* Network status checks */}
      <div className="bg-muted/5">
        <div className="container mx-auto px-4">
          <ClusterChecker>
            <AccountChecker />
          </ClusterChecker>
        </div>
      </div>

      {/* Main content */}
      <main className="flex-grow container mx-auto px-4 py-6">{children}</main>

      {/* Footer */}
      <footer className="border-t border-border py-6 bg-card/50">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">
          <p>
            Generated by{" "}
            <a
              className="text-primary hover:underline"
              href="https://github.com/solana-developers/create-solana-dapp"
              target="_blank"
              rel="noopener noreferrer"
            >
              create-solana-dapp
            </a>
          </p>
        </div>
      </footer>

      {/* Toast notifications */}
      <Toaster position="bottom-right" />
    </div>
  );
}
